version: "3"

services:
  limesurvey:
    image: sonyxme/limesurvey
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=limesurvey
    volumes:
      - ./uploads:/var/www/html/upload
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=limesurvey
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql
